/* Webhook provider payloads are intentionally untyped at the boundary and narrowed by runtime fields. */
/* eslint-disable @typescript-eslint/no-explicit-any */
import { DeleteObjectCommand, GetObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { Queue, Worker, type Job } from "bullmq";
import { Redis } from "ioredis";
import { createDecipheriv, createHash } from "node:crypto";
import { connect } from "node:net";
import { loadServiceEnvironment } from "@pulihkanaku/config";
import { createPostgresDatabase } from "@pulihkanaku/database";

loadServiceEnvironment();
const redisUrl=process.env.REDIS_URL??"redis://localhost:6379";
const connection=new Redis(redisUrl,{maxRetriesPerRequest:null});
const queue=new Queue("pulihkanaku",{connection,defaultJobOptions:{attempts:6,backoff:{type:"exponential",delay:30_000},removeOnComplete:500,removeOnFail:2000}});
const{pool}=createPostgresDatabase(process.env.DATABASE_URL??"postgres://pulihkanaku:pulihkanaku@localhost:5432/pulihkanaku",Number(process.env.DATABASE_POOL_MAX??10));
const storage=new S3Client({endpoint:process.env.STORAGE_ENDPOINT??"http://localhost:9000",region:process.env.STORAGE_REGION??"us-east-1",forcePathStyle:true,credentials:{accessKeyId:process.env.STORAGE_ACCESS_KEY??"minio",secretAccessKey:process.env.STORAGE_SECRET_KEY??"minio-development-only"}});
const bucket=process.env.STORAGE_BUCKET_PRIVATE??"pulihkanaku-private";
const delayFor=(attempt:number)=>Math.min(6*60*60*1000,30_000*2**attempt);
const log=(level:string,event:string,fields:Record<string,unknown>)=>console.log(JSON.stringify({timestamp:new Date().toISOString(),level,event,service:"pulihkanaku-worker",...fields}));
async function alert(type:string,detail:Record<string,unknown>){if(!process.env.ALERT_WEBHOOK_URL)return;try{await fetch(process.env.ALERT_WEBHOOK_URL,{method:"POST",headers:{"content-type":"application/json",...(process.env.ALERT_WEBHOOK_TOKEN?{authorization:`Bearer ${process.env.ALERT_WEBHOOK_TOKEN}`}:{})},body:JSON.stringify({type,severity:"ERROR",service:"pulihkanaku-worker",occurredAt:new Date().toISOString(),detail}),signal:AbortSignal.timeout(5000)})}catch(error){log("warn","alert.delivery_failed",{message:error instanceof Error?error.message:"unknown"})}}
function assertPayoutProviderOperational(){if((process.env.PAYOUT_PROVIDER??"xendit")!=="xendit")throw new Error("PAYOUT_PROVIDER_UNSUPPORTED");if(process.env.NODE_ENV==="production"&&!process.env.PAYOUT_PROVIDER_LICENSE_REFERENCE)throw new Error("PAYOUT_PROVIDER_LICENSE_NOT_VERIFIED")}

async function bodyBytes(body:unknown){const chunks:Uint8Array[]=[];for await(const chunk of body as AsyncIterable<Uint8Array>)chunks.push(chunk);return Buffer.concat(chunks)}
async function clamScan(buffer:Buffer){return new Promise<{clean:boolean;response:string}>((resolve,reject)=>{const socket=connect(Number(process.env.CLAMAV_PORT??3310),process.env.CLAMAV_HOST??"localhost");let response="";const timer=setTimeout(()=>socket.destroy(new Error("CLAMAV_TIMEOUT")),30_000);socket.on("connect",()=>{socket.write("zINSTREAM\0");for(let offset=0;offset<buffer.length;offset+=64*1024){const chunk=buffer.subarray(offset,offset+64*1024);const size=Buffer.alloc(4);size.writeUInt32BE(chunk.length);socket.write(size);socket.write(chunk)}socket.end(Buffer.alloc(4))});socket.on("data",chunk=>response+=chunk.toString("utf8"));socket.on("error",reject);socket.on("close",()=>{clearTimeout(timer);if(!response)return reject(new Error("CLAMAV_EMPTY_RESPONSE"));resolve({clean:response.includes("OK"),response:response.replace(/\0/g,"").trim().slice(0,500)})})})}
async function scanDocument(job:Job){const{table,documentId,objectKey}=job.data as{table:"verification_documents"|"assignment_evidence";documentId:string;objectKey:string};if(!["verification_documents","assignment_evidence"].includes(table))throw new Error("INVALID_SCAN_TABLE");await pool.query(`update ${table} set scan_status='SCANNING' where id=$1 and scan_status in ('PENDING','ERROR')`,[documentId]);try{const object=await storage.send(new GetObjectCommand({Bucket:bucket,Key:objectKey}));if(!object.Body)throw new Error("STORAGE_OBJECT_EMPTY");const result=await clamScan(await bodyBytes(object.Body));await pool.query(`update ${table} set scan_status=$2${table==="verification_documents"?",scan_result=$3":""} where id=$1`,table==="verification_documents"?[documentId,result.clean?"CLEAN":"INFECTED",JSON.stringify({engine:"clamav",response:result.response,scannedAt:new Date().toISOString()})]:[documentId,result.clean?"CLEAN":"INFECTED"]);if(!result.clean)await storage.send(new DeleteObjectCommand({Bucket:bucket,Key:objectKey}));return result}catch(error){await pool.query(`update ${table} set scan_status='ERROR'${table==="verification_documents"?",scan_result=$2":""} where id=$1`,table==="verification_documents"?[documentId,JSON.stringify({error:error instanceof Error?error.message:"SCAN_ERROR"})]:[documentId]);throw error}}

async function sendOtp(job:Job){const{identifier,channel,code,purpose}=job.data as{identifier:string;channel:string;code:string;purpose:string};if(channel==="EMAIL"&&process.env.EMAIL_PROVIDER==="resend"){const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${process.env.RESEND_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[identifier],subject:"Kode keamanan PulihkanAku",html:`<p>Kode ${purpose==="ACCOUNT_RECOVERY"?"pemulihan":"verifikasi"} Anda:</p><p style=\"font-size:28px;font-weight:700;letter-spacing:6px\">${code}</p><p>Kode berlaku 5 menit. Jangan berikan kepada siapa pun.</p>`})});if(!response.ok)throw new Error(`EMAIL_PROVIDER_${response.status}`);return{delivered:true}}
  const gateway=process.env.NOTIFICATION_GATEWAY_URL;if(gateway){const response=await fetch(gateway,{method:"POST",headers:{authorization:`Bearer ${process.env.NOTIFICATION_GATEWAY_TOKEN}`,"content-type":"application/json"},body:JSON.stringify({to:identifier,channel,template:"pulihkanaku_otp",parameters:{code,purpose,ttlMinutes:5}})});if(!response.ok)throw new Error(`NOTIFICATION_PROVIDER_${response.status}`);return{delivered:true}}
  if(process.env.NODE_ENV==="production")throw new Error("OTP_PROVIDER_NOT_CONFIGURED");return{delivered:false,development:true};
}
async function deliverNotification(job:Job){const row=(await pool.query<{id:string;user_id:string;title:string;body:string;email:string;phone_e164:string|null;email_enabled:number;whatsapp_enabled:number}>(`select n.id,n.user_id,n.title,n.body,u.email,u.phone_e164,coalesce(p.email_enabled,1) email_enabled,coalesce(p.whatsapp_enabled,1) whatsapp_enabled from notifications n join users u on u.id=n.user_id left join notification_preferences p on p.user_id=n.user_id where n.id=$1`,[job.data.notificationId])).rows[0];if(!row)return{skipped:true};const channel=row.phone_e164&&row.whatsapp_enabled?"WHATSAPP":"EMAIL";await pool.query(`insert into notification_deliveries(notification_id,channel,status,attempts) values($1,$2,'PROCESSING',1) on conflict(notification_id,channel) do update set status='PROCESSING',attempts=notification_deliveries.attempts+1,updated_at=now()`,[row.id,channel]);try{let providerReference:string|undefined;if(channel==="WHATSAPP"&&process.env.NOTIFICATION_GATEWAY_URL){const response=await fetch(process.env.NOTIFICATION_GATEWAY_URL,{method:"POST",headers:{authorization:`Bearer ${process.env.NOTIFICATION_GATEWAY_TOKEN}`,"content-type":"application/json"},body:JSON.stringify({to:row.phone_e164,channel,template:"pulihkanaku_notification",parameters:{title:row.title,body:row.body}})});if(!response.ok)throw new Error(`NOTIFICATION_PROVIDER_${response.status}`);providerReference=response.headers.get("x-provider-reference")??undefined}else if(channel==="EMAIL"&&row.email_enabled&&process.env.EMAIL_PROVIDER==="resend"){const response=await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${process.env.RESEND_API_KEY}`,"content-type":"application/json"},body:JSON.stringify({from:process.env.EMAIL_FROM,to:[row.email],subject:row.title,html:`<p>${row.body.replace(/[<>&]/g,char=>({"<":"&lt;",">":"&gt;","&":"&amp;"}[char]??char))}</p>`})});if(!response.ok)throw new Error(`EMAIL_PROVIDER_${response.status}`);providerReference=String((await response.json().catch(()=>({} as Record<string,unknown>)) as Record<string,unknown>).id??"")}else if(process.env.NODE_ENV==="production")throw new Error("NOTIFICATION_PROVIDER_NOT_CONFIGURED");await pool.query(`update notification_deliveries set status='SENT',provider_reference=$2,sent_at=now(),failure_code=null,updated_at=now() where notification_id=$1 and channel=$3`,[row.id,providerReference??null,channel]);return{sent:true,channel}}catch(error){await pool.query(`update notification_deliveries set status='RETRY_QUEUED',failure_code=$2,next_retry_at=now()+interval '5 minutes',updated_at=now() where notification_id=$1 and channel=$3`,[row.id,error instanceof Error?error.message.slice(0,100):"DELIVERY_ERROR",channel]);throw error}}
async function recordRisk(job:Job){const{userId,type,severity,score,source,referenceId,fingerprint,metadata}=job.data as{userId?:string;type:string;severity:string;score:number;source:string;referenceId?:string;fingerprint:string;metadata?:unknown};const inserted=await pool.query(`insert into risk_events(user_id,type,severity,score,source,reference_id,fingerprint,metadata) values($1,$2,$3,$4,$5,$6,$7,$8) on conflict(fingerprint) do nothing returning id`,[userId??null,type,severity,Math.max(0,Math.min(100,score)),source,referenceId??null,fingerprint,JSON.stringify(metadata??{})]);if(!inserted.rowCount)return{duplicate:true};if(userId){const aggregate=(await pool.query<{score:number}>(`select least(100,coalesce(sum(score),0))::int score from risk_events where user_id=$1 and created_at>now()-interval '24 hours'`,[userId])).rows[0]?.score??0;if(aggregate>=60){const priority=aggregate>=85?"CRITICAL":aggregate>=70?"HIGH":"MEDIUM";const riskCase=await pool.query<{id:string}>(`insert into risk_cases(user_id,priority,score,reason) select $1,$2,$3,$4 where not exists(select 1 from risk_cases where user_id=$1 and status='OPEN') returning id`,[userId,priority,aggregate,`Akumulasi sinyal risiko 24 jam: ${type}`]);if(riskCase.rowCount)await connection.publish("realtime:admin",JSON.stringify({type:"risk.case.created",caseId:riskCase.rows[0].id,userId,priority,score:aggregate}))}return{recorded:true,score:aggregate}}return{recorded:true}}
async function escalateSla(){const tickets=await pool.query<{id:string}>(`update support_tickets set priority='HIGH',updated_at=now() where status in ('OPEN','IN_PROGRESS') and sla_due_at<now() and priority<>'HIGH' returning id`);const disputes=await pool.query<{id:string}>(`update disputes set status='ESCALATED',version=version+1,updated_at=now() where status in ('OPEN','UNDER_REVIEW','WAITING_WORKER','WAITING_BUSINESS') and created_at<now()-interval '24 hours' returning id`);if((tickets.rowCount??0)+(disputes.rowCount??0)>0)await connection.publish("realtime:admin",JSON.stringify({type:"sla.escalated",tickets:tickets.rows.map(x=>x.id),disputes:disputes.rows.map(x=>x.id)}));return{tickets:tickets.rowCount,disputes:disputes.rowCount}}
function decryptAccount(ciphertext:string,iv:string){let key:string|Buffer|undefined=process.env.PAYOUT_ENCRYPTION_KEY;if(!key&&process.env.NODE_ENV!=="production")key=createHash("sha256").update("pulihkanaku-local-payout-key").digest();if(!key)throw new Error("PAYOUT_ENCRYPTION_KEY_MISSING");const raw=Buffer.isBuffer(key)?key:Buffer.from(key,"base64url");if(raw.length!==32)throw new Error("PAYOUT_ENCRYPTION_KEY_INVALID");const encrypted=Buffer.from(ciphertext,"base64url");const tag=encrypted.subarray(encrypted.length-16);const data=encrypted.subarray(0,-16);const decipher=createDecipheriv("aes-256-gcm",raw,Buffer.from(iv,"base64url"));decipher.setAuthTag(tag);return Buffer.concat([decipher.update(data),decipher.final()]).toString("utf8")}
async function processPayout(job:Job){const row=(await pool.query<{id:string;amount:string;status:string;idempotency_key:string;bank_code:string;account_name:string;account_number_encrypted:string;encryption_iv:string}>(`select p.id,p.amount,p.status,p.idempotency_key,a.bank_code,a.account_name,a.account_number_encrypted,a.encryption_iv from payouts p join worker_payment_accounts a on a.id=p.payment_account_id where p.id=$1 and p.status in ('SCHEDULED','RETRY_QUEUED','FAILED') and a.status='VERIFIED' for update`,[job.data.payoutId])).rows[0];if(!row)return{skipped:true};const key=process.env.XENDIT_SECRET_API_KEY;if(!key)throw new Error("XENDIT_SECRET_API_KEY_MISSING");await pool.query(`update payouts set status='PROCESSING',processed_at=now(),retry_count=retry_count+1,next_retry_at=null,updated_at=now() where id=$1`,[row.id]);const response=await fetch(`${process.env.XENDIT_API_URL??"https://api.xendit.co"}/v2/payouts`,{method:"POST",headers:{authorization:`Basic ${Buffer.from(`${key}:`).toString("base64")}`,"content-type":"application/json","idempotency-key":row.idempotency_key},body:JSON.stringify({reference_id:row.id,channel_code:`ID_${row.bank_code}`,channel_properties:{account_number:decryptAccount(row.account_number_encrypted,row.encryption_iv),account_holder_name:row.account_name},amount:Number(row.amount),currency:"IDR",description:"Pembayaran pekerjaan PulihkanAku"})});const data=await response.json().catch(()=>({})) as Record<string,unknown>;if(!response.ok){const failure=String(data.error_code??`HTTP_${response.status}`);const terminal=response.status>=400&&response.status<500&&![408,409,429].includes(response.status);await pool.query(`update payouts set status=$2,failure_code=$3,next_retry_at=case when $2='RETRY_QUEUED' then now()+($4*interval '1 millisecond') else null end,updated_at=now() where id=$1`,[row.id,terminal?"FAILED":"RETRY_QUEUED",failure,delayFor(job.attemptsMade)]);if(terminal)return{failed:true,terminal:true,failure};throw new Error(`XENDIT_${failure}`)}await pool.query(`update payouts set status='PROCESSING',provider_reference=$2,failure_code=null,updated_at=now() where id=$1`,[row.id,String(data.id??data.payout_id??"")]);return{accepted:true,providerReference:data.id??data.payout_id}}

async function dispatchDue(){const rows=await pool.query<{id:string;retry_count:number}>(`select id,retry_count from payouts where status in ('SCHEDULED','RETRY_QUEUED') and coalesce(next_retry_at,now())<=now() order by created_at limit 100`);for(const row of rows.rows)await queue.add("payout.process",{payoutId:row.id},{jobId:`payout-${row.id}-${row.retry_count}`});return{queued:rows.rowCount}}
async function processWebhook(job:Job){const client=await pool.connect();try{await client.query("begin");const webhook=(await client.query<{id:string;payload:Record<string,any>;status:string}>(`select id,payload,status from provider_webhooks where id=$1 for update`,[job.data.webhookId])).rows[0];if(!webhook||webhook.status==="PROCESSED"){await client.query("rollback");return{duplicate:true}}const data=(webhook.payload.data??webhook.payload) as Record<string,any>;const providerRef=String(data.id??data.payout_id??"");const internalRef=String(data.reference_id??data.external_id??"");const payout=(await client.query<{id:string;assignment_id:string;amount:string;status:string}>(`select id,assignment_id,amount,status from payouts where provider_reference=$1 or id=$2 limit 1 for update`,[providerRef,internalRef])).rows[0];if(!payout)throw new Error("WEBHOOK_PAYOUT_NOT_FOUND");const providerStatus=String(data.status??"").toUpperCase();const next=providerStatus==="SUCCEEDED"?"PAID":providerStatus==="REVERSED"?"REVERSED":providerStatus==="FAILED"||providerStatus==="REJECTED"?"FAILED":"PROCESSING";await client.query(`update payouts set status=$2,provider_reference=coalesce(provider_reference,$3),paid_at=case when $2='PAID' then now() else paid_at end,failure_code=$4,updated_at=now() where id=$1`,[payout.id,next,providerRef,data.failure_code??null]);if(next==="PAID")await client.query(`insert into ledger_entries(job_id,assignment_id,type,direction,amount,currency,reference) select job_id,id,'PAYOUT','DEBIT',$2,'IDR',$3 from job_assignments where id=$1 on conflict(reference) do nothing`,[payout.assignment_id,payout.amount,`payout:${payout.id}`]);const actual=Number(data.amount??data.destination_amount??payout.amount);const expected=Number(payout.amount);await client.query(`insert into reconciliation_records(type,provider_reference,internal_reference,status,expected_amount,actual_amount,variance) values('PAYOUT',$1,$2,$3,$4,$5,$6) on conflict(provider_reference) do update set status=excluded.status,actual_amount=excluded.actual_amount,variance=excluded.variance`,[providerRef,payout.id,next==="PAID"&&actual===expected?"MATCHED":next==="PROCESSING"?"PENDING":"REVIEW_REQUIRED",expected,actual,actual-expected]);await client.query(`update provider_webhooks set status='PROCESSED',processed_at=now() where id=$1`,[webhook.id]);await client.query("commit");return{payoutId:payout.id,status:next}}catch(error){await client.query("rollback");throw error}finally{client.release()}}

const processor=async(job:Job)=>{switch(job.name){case"document.scan":return scanDocument(job);case"notification.send-otp":return sendOtp(job);case"notification.deliver":return deliverNotification(job);case"risk.record":return recordRisk(job);case"operations.escalate-sla":return escalateSla();case"payout.process":assertPayoutProviderOperational();return processPayout(job);case"payout.dispatch-due":return dispatchDue();case"payout.webhook":return processWebhook(job);default:throw new Error(`UNKNOWN_JOB:${job.name}`)}};
const worker=new Worker("pulihkanaku",processor,{connection,concurrency:Number(process.env.WORKER_CONCURRENCY??8)});
worker.on("completed",job=>log("info","queue.completed",{jobId:job.id,jobName:job.name,attempts:job.attemptsMade}));worker.on("failed",async(job,error)=>{const terminal=!!job&&job.attemptsMade>=(job.opts.attempts??1);log(terminal?"error":"warn","queue.failed",{jobId:job?.id,jobName:job?.name,attempts:job?.attemptsMade,terminal,error:error.message.slice(0,160)});if(job?.name==="payout.process"&&terminal)await pool.query(`update payouts set status='FAILED',failure_code=coalesce(failure_code,$2),next_retry_at=null,updated_at=now() where id=$1 and status='RETRY_QUEUED'`,[job.data.payoutId,error.message.slice(0,100)]);if(terminal)void alert("QUEUE_TERMINAL_FAILURE",{jobId:job?.id,jobName:job?.name,error:error.message.slice(0,160)})});
await queue.upsertJobScheduler("payout-due-every-minute",{every:60_000},{name:"payout.dispatch-due",data:{}});
await queue.upsertJobScheduler("operations-sla-every-five-minutes",{every:300_000},{name:"operations.escalate-sla",data:{}});
const heartbeat=async()=>connection.set("service:worker:heartbeat",new Date().toISOString(),"EX",45);
await heartbeat();const heartbeatTimer=setInterval(()=>void heartbeat(),15_000);heartbeatTimer.unref();
const shutdown=async()=>{clearInterval(heartbeatTimer);await worker.close();await queue.close();await connection.del("service:worker:heartbeat");await connection.quit();await pool.end();process.exit(0)};process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);
