"use client";

import { ArrowRight, CheckCircle2, FileCheck2, ShieldCheck } from "lucide-react";
import { useState } from "react";

type Role="WORKER"|"BUSINESS_OWNER";

export function OnboardingForm({role}:{role:Role}){
  const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[done,setDone]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget);const list=(name:string)=>String(form.get(name)??"").split(",").map(x=>x.trim()).filter(Boolean);const payload=role==="WORKER"?{birthYear:Number(form.get("birthYear")),bio:String(form.get("bio")??""),skills:list("skills"),availability:list("availability"),preferredJobTypes:list("jobTypes"),vehicles:list("vehicles"),maxDistanceKm:Number(form.get("maxDistanceKm")),emergencyContactName:String(form.get("emergencyContactName")??""),emergencyContactPhone:String(form.get("emergencyContactPhone")??"")}:{representativeName:String(form.get("representativeName")??""),district:String(form.get("district")??""),address:String(form.get("address")??""),nib:String(form.get("nib")??""),jobRulesAccepted:form.get("jobRulesAccepted")==="on"};
    try{const saved=await fetch("/api/v1/onboarding",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const savedResult=await saved.json()as{success:boolean;error?:{message?:string}};if(!saved.ok||!savedResult.success)throw new Error(savedResult.error?.message??"Profil belum dapat disimpan.");const verification=new FormData();const identity=form.get("identityDocument");const business=form.get("businessDocument");if(identity instanceof File&&identity.size)verification.set("identityDocument",identity);if(business instanceof File&&business.size)verification.set("businessDocument",business);const submitted=await fetch("/api/v1/verifications",{method:"POST",body:verification});const submittedResult=await submitted.json()as{success:boolean;error?:{message?:string}};if(!submitted.ok||!submittedResult.success)throw new Error(submittedResult.error?.message??"Pengajuan verifikasi belum dapat dikirim.");setDone(true)}catch(cause){setError(cause instanceof Error?cause.message:"Onboarding belum dapat diselesaikan.")}finally{setLoading(false)}}
  if(done)return <div className="onboarding-success"><CheckCircle2/><h2>Pengajuan berhasil dikirim</h2><p>Tim verifikasi akan memeriksa data dan dokumenmu. Kamu tetap dapat menggunakan fitur dasar selama proses review.</p><a className="primary-button" href={role==="WORKER"?"/app":"/business"}>Kembali ke dashboard <ArrowRight/></a></div>;
  return <form className="onboarding-form" onSubmit={submit}>
    <section className="onboarding-section"><div className="onboarding-heading"><span>1</span><div><h2>Lengkapi profil</h2><p>Informasi ini membantu keamanan dan kecocokan pekerjaan.</p></div></div>{role==="WORKER"?<><div className="auth-grid"><Field label="Tahun lahir"><input name="birthYear" type="number" min="1940" max={new Date().getFullYear()-17} required/></Field><Field label="Jarak kerja maksimal"><select name="maxDistanceKm" defaultValue="10"><option value="5">5 km</option><option value="10">10 km</option><option value="20">20 km</option><option value="50">50 km</option></select></Field></div><Field label="Tentang dirimu (opsional)"><textarea name="bio" maxLength={500} placeholder="Ceritakan pengalaman praktis secara singkat."/></Field><Field label="Kemampuan"><input name="skills" required placeholder="Contoh: packing, kasir, foto produk"/><small>Pisahkan beberapa kemampuan dengan koma.</small></Field><div className="auth-grid"><Field label="Ketersediaan"><input name="availability" required placeholder="Pagi, akhir pekan"/></Field><Field label="Jenis kerja diminati"><input name="jobTypes" required placeholder="Shift harian, proyek"/></Field><Field label="Kendaraan (opsional)"><input name="vehicles" placeholder="Motor"/></Field><Field label="Nama kontak darurat (opsional)"><input name="emergencyContactName"/></Field></div><Field label="Nomor kontak darurat (opsional)"><input name="emergencyContactPhone" inputMode="tel" placeholder="081234567890"/></Field></>:<><div className="auth-grid"><Field label="Nama penanggung jawab"><input name="representativeName" required minLength={3}/></Field><Field label="Kecamatan"><input name="district" required/></Field></div><Field label="Alamat lengkap bisnis"><textarea name="address" required minLength={10}/></Field><Field label="NIB (opsional untuk UMKM awal)"><input name="nib" maxLength={50}/></Field><label className="onboarding-check"><input name="jobRulesAccepted" type="checkbox" required/><span>Saya menyetujui aturan lowongan: tidak meminta deposit, tidak memungut biaya dari pekerja, dan nominal bayaran harus jelas.</span></label></>}</section>
    <section className="onboarding-section" id="verifikasi"><div className="onboarding-heading"><span>2</span><div><h2>Ajukan verifikasi</h2><p>Dokumen disimpan privat dan hanya dapat dibuka oleh pemilik serta petugas verifikasi.</p></div></div><div className="upload-grid"><Upload name="identityDocument" label="Dokumen identitas" hint="KTP atau identitas resmi"/>{role==="BUSINESS_OWNER"&&<Upload name="businessDocument" label="Bukti bisnis" hint="NIB, dokumen usaha, atau foto tempat usaha"/>}</div><div className="document-policy"><ShieldCheck/><span>JPG, PNG, atau PDF · maksimal 5 MB per file · URL publik tidak dibuat.</span></div></section>
    {error&&<div className="auth-error" role="alert">{error}</div>}<button className="primary-button full onboarding-submit" disabled={loading}>{loading?"Menyimpan dan mengirim…":<>Simpan dan ajukan verifikasi <ArrowRight/></>}</button>
  </form>
}

function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="auth-field"><span>{label}</span>{children}</label>}
function Upload({name,label,hint}:{name:string;label:string;hint:string}){return <label className="upload-card"><FileCheck2/><strong>{label}</strong><span>{hint}</span><input name={name} type="file" accept="image/jpeg,image/png,application/pdf" required/></label>}
