"use client";
import { ArrowRight, LockKeyhole, WalletCards, WifiOff } from "lucide-react";
import { useEffect, useState } from "react";

export function PayoutForm() {
  const [loading,setLoading]=useState(false),[error,setError]=useState(""),[online,setOnline]=useState(()=>typeof navigator==="undefined"?true:navigator.onLine!==false);
  const [done,setDone]=useState<{bankCode:string;lastFour:string}|null>(null);
  useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);window.addEventListener("online",on);window.addEventListener("offline",off);return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",off)}},[]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!online){setError("Koneksi terputus. Data rekening belum dikirim.");return}setLoading(true);setError("");const form=new FormData(event.currentTarget);try{const response=await fetch("/api/v1/payout-accounts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({bankCode:String(form.get("bankCode")),accountName:String(form.get("accountName")),accountNumber:String(form.get("accountNumber"))})});const result=await response.json()as{success:boolean;data?:{bankCode:string;lastFour:string};error?:{message:string;requestId?:string}};if(!response.ok||!result.success||!result.data)throw new Error(`${result.error?.message??"Provider payout belum dapat menyimpan rekening."}${result.error?.requestId?` Referensi: ${result.error.requestId}`:""}`);setDone(result.data)}catch(cause){setError(cause instanceof Error?cause.message:"Provider payout belum tersedia. Data tidak diubah; silakan coba lagi.")}finally{setLoading(false)}}
  if(done)return <div className="onboarding-success"><WalletCards/><h2>Rekening tersimpan</h2><p>{done.bankCode} •••• {done.lastFour} sedang menunggu verifikasi nama pemilik. Nomor lengkap tidak pernah ditampilkan kembali.</p><a className="primary-button" href="/app">Kembali ke dashboard <ArrowRight/></a></div>;
  return <form className="onboarding-form" onSubmit={submit}>{!online&&<div className="network-banner"><WifiOff/>Offline — penyimpanan dinonaktifkan agar data rekening tidak hilang.</div>}<div className="auth-field"><label htmlFor="bankCode">Bank atau dompet digital</label><select id="bankCode" name="bankCode" required defaultValue=""><option value="" disabled>Pilih tujuan payout</option>{["BCA","BNI","BRI","MANDIRI","BSI","JAGO","SEABANK","DANA","GOPAY","OVO","SHOPEEPAY"].map(x=><option key={x}>{x}</option>)}</select></div><div className="auth-field"><label htmlFor="accountName">Nama pemilik rekening</label><input id="accountName" name="accountName" required minLength={3} autoComplete="name"/></div><div className="auth-field"><label htmlFor="accountNumber">Nomor rekening/akun</label><input id="accountNumber" name="accountNumber" required inputMode="numeric" pattern="[0-9 ]{8,24}" autoComplete="off"/></div><div className="security-callout"><LockKeyhole/><span><strong>Dienkripsi sebelum disimpan.</strong>Admin hanya melihat empat digit terakhir. Perubahan rekening selalu masuk antrean verifikasi ulang.</span></div>{error&&<div className="auth-error" role="alert">{error}<br/><small>Periksa koneksi lalu tekan tombol simpan untuk mencoba kembali.</small></div>}<button className="primary-button full auth-submit" disabled={loading||!online}>{loading?"Mengenkripsi dan menyimpan…":<>Simpan rekening payout <ArrowRight/></>}</button></form>;
}
