"use client";

import { Check, ChevronDown, FileText, RotateCcw, X } from "lucide-react";
import { useState } from "react";

export type VerificationQueueItem = { id:string;subject_type:string;status:string;submitted_at:number;version:number;full_name:string;email:string;business_name:string|null;document_count:number };
type Detail=VerificationQueueItem&{address?:string;representative_name?:string;documents:{id:string;type:string;file_name:string;mime_type:string;size_bytes:number}[]};

export function VerificationReview({initialItems}:{initialItems:VerificationQueueItem[]}){
  const[items,setItems]=useState(initialItems);const[detail,setDetail]=useState<Detail|null>(null);const[error,setError]=useState("");
  async function open(id:string){const response=await fetch(`/api/v1/verifications/${id}`);const result=await response.json()as{success:boolean;data?:Detail;error?:{message:string}};if(result.success&&result.data)setDetail(result.data);else setError(result.error?.message??"Pengajuan gagal dimuat.")}
  async function review(decision:"APPROVE"|"REJECT"|"REVISION"){if(!detail)return;const reason=decision==="APPROVE"?"Dokumen dan profil sesuai kebijakan verifikasi.":window.prompt(decision==="REVISION"?"Jelaskan data yang perlu diperbaiki:":"Jelaskan alasan penolakan:");if(decision!=="APPROVE"&&(!reason||reason.trim().length<10))return;const response=await fetch(`/api/v1/verifications/${detail.id}/review`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({decision,reason,expectedVersion:detail.version,expiryDays:365})});const result=await response.json()as{success:boolean;error?:{message:string}};if(!result.success){setError(result.error?.message??"Review gagal disimpan.");return}setItems(current=>current.filter(item=>item.id!==detail.id));setDetail(null)}
  return <section className="verification-console"><div className="section-title"><div><p className="eyebrow">Verification operations</p><h2>Antrean pengajuan</h2></div><span className="status warning">{items.length} menunggu</span></div>{error&&<div className="auth-error">{error}</div>}{items.length===0?<p className="queue-empty">Tidak ada pengajuan yang menunggu review.</p>:<div className="verification-list">{items.map(item=><button key={item.id} onClick={()=>open(item.id)}><span className="verification-avatar">{item.subject_type==="WORKER"?"W":"B"}</span><span><strong>{item.business_name??item.full_name}</strong><small>{item.email} · {item.document_count} dokumen</small></span><span className="status warning">{item.status}</span><ChevronDown/></button>)}</div>}{detail&&<div className="review-panel"><div className="review-panel-head"><div><p className="eyebrow">{detail.subject_type}</p><h3>{detail.business_name??detail.full_name}</h3><small>{detail.email}</small></div><button className="icon-button" onClick={()=>setDetail(null)} aria-label="Tutup"><X/></button></div>{detail.business_name&&<dl><div><dt>Penanggung jawab</dt><dd>{detail.representative_name||"-"}</dd></div><div><dt>Alamat</dt><dd>{detail.address||"-"}</dd></div></dl>}<div className="review-documents">{detail.documents.map(doc=><a key={doc.id} href={`/api/v1/documents/${doc.id}`} target="_blank" rel="noreferrer"><FileText/><span><strong>{doc.type}</strong><small>{doc.file_name} · {(doc.size_bytes/1024).toFixed(0)} KB</small></span></a>)}</div><div className="review-actions"><button className="outline-button" onClick={()=>review("REVISION")}><RotateCcw/>Minta revisi</button><button className="outline-button danger-button" onClick={()=>review("REJECT")}><X/>Tolak</button><button className="primary-button" onClick={()=>review("APPROVE")}><Check/>Setujui</button></div></div>}</section>
}
