import { getD1 } from "@/db";
import { fail,ok,requestId } from "@/lib/api-response";
import { assertAuthorized } from "@/lib/domain/authorization";
import { requireApiIdentity } from "@/lib/identity";
type Context={params:Promise<{id:string}>};
export async function POST(request:Request,context:Context){
  const reqId=requestId(request);const identity=await requireApiIdentity(request);if(!identity)return fail("UNAUTHENTICATED","Silakan masuk untuk meninjau verifikasi.",reqId,401);try{assertAuthorized(identity.role,"verification:review")}catch{return fail("FORBIDDEN","Akun ini tidak dapat meninjau verifikasi.",reqId,403)}
  const{id}=await context.params;const body=await request.json().catch(()=>null)as{decision?:"APPROVE"|"REJECT"|"REVISION";reason?:string;expectedVersion?:number;expiryDays?:number}|null;if(!body?.decision||!Number.isInteger(body.expectedVersion)||((body.decision!=="APPROVE")&&(!body.reason?.trim()||body.reason.trim().length<10)))return fail("VALIDATION_ERROR","Keputusan, versi, dan alasan yang jelas diperlukan.",reqId,422);
  const d1=getD1();const row=await d1.prepare("SELECT id,user_id,subject_type,business_id,status,version FROM verification_submissions WHERE id=? LIMIT 1").bind(id).first<{id:string;user_id:string;subject_type:string;business_id:string|null;status:string;version:number}>();if(!row)return fail("VERIFICATION_NOT_FOUND","Pengajuan tidak ditemukan.",reqId,404);if(!["SUBMITTED","UNDER_REVIEW"].includes(row.status))return fail("VERIFICATION_ALREADY_REVIEWED","Pengajuan ini sudah ditinjau.",reqId,409);if(row.version!==body.expectedVersion)return fail("VERSION_CONFLICT","Pengajuan sudah berubah. Muat ulang data.",reqId,409);
  const next=body.decision==="APPROVE"?"APPROVED":body.decision==="REJECT"?"REJECTED":"NEEDS_REVISION";const now=Date.now();const expiry=body.decision==="APPROVE"?now+Math.min(Math.max(Number(body.expiryDays)||365,30),730)*86_400_000:null;const target=row.subject_type==="WORKER"?d1.prepare("UPDATE worker_profiles SET verification_level=?,onboarding_status=?,profile_completion=?,updated_at=? WHERE user_id=?").bind(body.decision==="APPROVE"?"IDENTITY_VERIFIED":"BASIC",body.decision==="REVISION"?"NEEDS_REVISION":body.decision==="APPROVE"?"VERIFIED":"COMPLETE",body.decision==="APPROVE"?100:80,now,row.user_id):d1.prepare("UPDATE businesses SET verification_status=?,trust_score=?,updated_at=? WHERE id=?").bind(body.decision==="APPROVE"?"VERIFIED":next,body.decision==="APPROVE"?50:0,now,row.business_id);
  const[updated]=await d1.batch([d1.prepare("UPDATE verification_submissions SET status=?,reviewed_at=?,reviewed_by_user_id=?,review_reason=?,expires_at=?,version=version+1,updated_at=? WHERE id=? AND version=? AND status IN ('SUBMITTED','UNDER_REVIEW')").bind(next,now,identity.id,body.reason?.trim().slice(0,1000)??null,expiry,now,id,row.version),target,d1.prepare("INSERT INTO audit_logs (id,actor_email,actor_role,action,entity_type,entity_id,previous_state,next_state,request_id,reason,created_at) VALUES (?,?,?,'VERIFICATION_REVIEWED','VERIFICATION',?,?,?,?,?,?)").bind(crypto.randomUUID(),identity.email,identity.role,id,row.status,next,reqId,body.reason?.trim().slice(0,1000)??null,now)]);if(!updated.success||(updated.meta.changes??0)!==1)return fail("VERSION_CONFLICT","Pengajuan sudah berubah.",reqId,409);return ok({id,status:next,expiresAt:expiry?new Date(expiry).toISOString():null,version:row.version+1});
}
