import { BadRequestException, Body, Controller, ForbiddenException, Get, Headers, HttpCode, Inject, Injectable, NotFoundException, Param, Post, Query, Req, UnauthorizedException } from "@nestjs/common";
import { IsIn, IsString, MaxLength, MinLength } from "class-validator";
import { createHash, randomUUID, timingSafeEqual } from "node:crypto";
import type { Request } from "express";
import type { Pool } from "pg";
import type { Queue } from "bullmq";
import { AuthService } from "./auth.js";
import { POSTGRES, RateLimitService, WORK_QUEUE } from "../infrastructure.module.js";

const financeRoles = new Set(["FINANCE_ADMIN", "OPERATIONS_ADMIN", "SUPER_ADMIN"]);
const secureEqual=(a:string,b:string)=>{const left=createHash("sha256").update(a).digest();const right=createHash("sha256").update(b).digest();return timingSafeEqual(left,right)};
export class ResolveReconciliationDto { @IsIn(["MATCHED","ADJUSTED","IGNORED"]) status!:string; @IsString() @MinLength(20) @MaxLength(1000) note!:string; }

@Injectable()
export class PayoutService{
  constructor(@Inject(POSTGRES) private readonly pool:Pool,@Inject(WORK_QUEUE) private readonly queue:Queue,private readonly auth:AuthService,private readonly cache:RateLimitService){}
  private async actor(request:Request){return this.auth.sessionFrom(request)}
  async list(request:Request,page=1){const actor=await this.actor(request);const admin=financeRoles.has(actor.role);const limit=50,offset=(Math.max(1,page)-1)*limit;const values=admin?[limit,offset]:[actor.user_id,limit,offset];const sql=admin?`select p.id,p.assignment_id,p.worker_user_id,p.amount,p.status,p.provider_reference,p.retry_count,p.next_retry_at,p.failure_code,p.created_at,p.updated_at from payouts p order by p.created_at desc limit $1 offset $2`:`select p.id,p.assignment_id,p.amount,p.status,p.provider_reference,p.retry_count,p.next_retry_at,p.failure_code,p.created_at,p.updated_at from payouts p where p.worker_user_id=$1 order by p.created_at desc limit $2 offset $3`;return{items:(await this.pool.query(sql,values)).rows,page:Math.max(1,page),pageSize:limit};}
  async summary(request:Request){const actor=await this.actor(request);return this.cache.cached(`payout-summary:${actor.user_id}:${actor.role}`,30,async()=>{const values=financeRoles.has(actor.role)?[]:[actor.user_id];const where=values.length?"where worker_user_id=$1":"";return(await this.pool.query(`select status,count(*)::int count,coalesce(sum(amount),0)::text amount from payouts ${where} group by status`,values)).rows;});}
  async retry(request:Request,id:string){const actor=await this.actor(request);if(!financeRoles.has(actor.role))throw new ForbiddenException("Hanya finance/operations admin yang dapat mengulang payout.");const changed=await this.pool.query(`update payouts set status='RETRY_QUEUED',next_retry_at=now(),failure_code=null,version=version+1,updated_at=now() where id=$1 and status in ('FAILED','RETRY_QUEUED') and retry_count<6 returning id,retry_count`,[id]);if(!changed.rowCount)throw new BadRequestException("Payout tidak dapat diulang atau batas retry tercapai.");await this.queue.add("payout.process",{payoutId:id,manual:true,actorUserId:actor.user_id},{jobId:`payout:${id}:${changed.rows[0].retry_count}`});return{id,status:"RETRY_QUEUED"};}
  async ingestWebhook(provider:string,eventId:string,eventType:string,payload:unknown){const inserted=await this.pool.query(`insert into provider_webhooks(provider,event_id,event_type,payload,status) values($1,$2,$3,$4,'RECEIVED') on conflict(provider,event_id) do nothing returning id`,[provider,eventId,eventType,payload]);if(inserted.rowCount)await this.queue.add("payout.webhook",{webhookId:inserted.rows[0].id},{jobId:`webhook:${provider}:${eventId}`});return{accepted:true,duplicate:!inserted.rowCount};}
  async reconciliation(request:Request,status?:string){const actor=await this.actor(request);if(!financeRoles.has(actor.role))throw new ForbiddenException("Akses rekonsiliasi ditolak.");const values=status?[status]:[];const where=status?"where status=$1":"";return{items:(await this.pool.query(`select id,type,provider_reference,internal_reference,status,expected_amount,actual_amount,variance,note,resolved_at,created_at from reconciliation_records ${where} order by created_at desc limit 200`,values)).rows};}
  async resolve(request:Request,id:string,body:ResolveReconciliationDto){const actor=await this.actor(request);if(!financeRoles.has(actor.role))throw new ForbiddenException("Akses rekonsiliasi ditolak.");const result=await this.pool.query(`update reconciliation_records set status=$1,note=$2,resolved_by_user_id=$3,resolved_at=now() where id=$4 and status in ('UNMATCHED','MISMATCH','REVIEW_REQUIRED') returning id,status,resolved_at`,[body.status,body.note.trim(),actor.user_id,id]);if(!result.rowCount)throw new NotFoundException("Rekonsiliasi tidak ditemukan atau sudah selesai.");await this.pool.query(`insert into audit_logs(actor_email,actor_role,action,entity_type,entity_id,previous_state,next_state,request_id,reason) values($1,$2,'RECONCILIATION_RESOLVED','RECONCILIATION',$3,'REVIEW_REQUIRED',$4,$5,$6)`,[actor.email,actor.role,id,body.status,request.headers["x-request-id"]??randomUUID(),body.note.trim()]);return result.rows[0];}
}

@Controller("payouts") export class PayoutController{constructor(private readonly payouts:PayoutService){}@Get() list(@Req() req:Request,@Query("page") page?:string){return this.payouts.list(req,Number(page??1))}@Get("summary") summary(@Req() req:Request){return this.payouts.summary(req)}@Post(":id/retry") retry(@Req() req:Request,@Param("id") id:string){return this.payouts.retry(req,id)}}

@Controller("payments/webhooks") export class WebhookController{
  constructor(private readonly payouts:PayoutService){}
  @Post(":provider") @HttpCode(200) async receive(@Param("provider") provider:string,@Headers("x-callback-token") token:string|undefined,@Headers("webhook-id") webhookId:string|undefined,@Body() payload:Record<string,unknown>){if(provider!=="xendit")throw new NotFoundException("Provider tidak didukung.");const expected=process.env.XENDIT_WEBHOOK_TOKEN;if(!expected||!token||!secureEqual(expected,token))throw new UnauthorizedException("Webhook signature tidak valid.");const eventId=webhookId??String(payload.id??payload.event_id??"");const eventType=String(payload.event??payload.event_type??payload.status??"unknown");if(!eventId)throw new BadRequestException("Webhook event id diperlukan.");return this.payouts.ingestWebhook(provider,eventId,eventType,payload)}
}

@Controller("admin/reconciliation") export class ReconciliationController{constructor(private readonly payouts:PayoutService){}@Get() list(@Req() req:Request,@Query("status") status?:string){return this.payouts.reconciliation(req,status)}@Post(":id/resolve") resolve(@Req() req:Request,@Param("id") id:string,@Body() body:ResolveReconciliationDto){return this.payouts.resolve(req,id,body)}}
